
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Poppins } from "next/font/google";
import { FloatingDock } from "./components/floating-dock";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
  variable: "--font-poppins", 
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Anil's Portfolio",
  icons: {
    icon: "/1704534290885-modified.png"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${poppins.variable} ${geistMono.variable}`}>
      <head>
        <link rel="icon" href="/1704534290885-modified.png" type="image/png" />
      </head>
      <body
        className={` antialiased`}
      >
        <FloatingDock />
        {children}
      </body>
    </html>
  );
}

